### ISSUE TITLE
Red Pizza Bag crashes Server

### ISSUE THREAD

**Issue by Clasko** [Tiviacz1337/PizzaCraft#44]
The Server crashes when you try to use the Red Pizza Bag on 1.16.5. Mod Version is 3.0.5

```
[04Jul2021 00:02:50.154] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_235333_g_()Lnet/minecraft/util/text/IFormattableTextComponent;
        at com.tiviacz.pizzacraft.tileentity.PizzaBagTileEntity.func_145748_c_(PizzaBagTileEntity.java:160) ~[pizzacraft:1.16.5-3.0.5]
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:226) ~[forge:?]
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:190) ~[forge:?]
        at com.tiviacz.pizzacraft.tileentity.PizzaBagTileEntity.openGUI(PizzaBagTileEntity.java:171) ~[pizzacraft:1.16.5-3.0.5]
        at com.tiviacz.pizzacraft.blocks.PizzaBagBlock.func_225533_a_(PizzaBagBlock.java:67) ~[pizzacraft:1.16.5-3.0.5]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[04Jul2021 00:02:50.156] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID fc7cdf2b-0059-480b-864b-4901cc6093a5
```

Let me know if you need more Infos.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3429298
