### ISSUE TITLE
Setting all seed drops to false in config file crashes game on load

### ISSUE THREAD

**Issue by wetbrownsauce** [Tiviacz1337/PizzaCraft#6]
**Versions**
Minecraft v1.12.2
Pizzacraft v1.2.0
Forge v14.23.4.2761 and up

**Expected Behavior**
- Disable all seed drops through config file options
- Seeds no longer drop from grass

**Actual Behavior**
- Disable all seed drops through config file options
- Game crashes when loading

**Steps to Reproduce**
- Install the latest PizzaCraft and Forge 14.23.4.2761 or later
- Set **ALL** seed drops in the config file to false
- Launch game

**Description**
The following results in a game crash:
1. Setting ALL seed drop lines in the config to false (olives can still be enabled)

The following DOES NOT result in a game crash:
1. Setting SOME, but not all, seed drop lines in the config to false
2. Toggling the global B:"Grass drop seeds"

The game will only crash when ALL seed drops are disabled, independent of the B:"Grass drop seeds" line as if it is ignored completely. **Further, leaving all seed drops set to true and setting B:"Grass drop seeds" to false does not prevent seeds from dropping.**  

**Crash Report**
[Full Report on Pastebin](https://pastebin.com/6QXJrAcx)

> java.lang.ExceptionInInitializerError
	at com.tiviacz.pizzacraft.init.base.BlockBase.<init>(BlockBase.java:25)
	at com.tiviacz.pizzacraft.objects.blocks.BlockPizza.<init>(BlockPizza.java:52)
	at com.tiviacz.pizzacraft.init.ModBlocks.<clinit>(ModBlocks.java:34)
	at com.tiviacz.pizzacraft.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_RegistryHandler_onBlockRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at com.tiviacz.pizzacraft.init.ModItems.<clinit>(ModItems.java:52)
	... 20 more

**Comment by DWX12** [comment]
Thanks for posting this. I knew Pizzacraft was doing something funky when I was trying to disable the seeds. I think olives are independent from the seeds, but unsure if it still crashes if those two are disabled. Atleast I know that I can enable just one to not have it crash.

Again, thanks for posting this and hope that the author will get it fixed soon.

**Comment by Tiviacz1337** [comment]
Fixed in 1.2.5

**Comment by Tiviacz1337** [comment]
Fixed in PizzaCraft 1.2.5
