### ISSUE TITLE
Crash on server 1.19 (not 1.19.1 or 1.19.2)

### ISSUE THREAD

**Issue by Flouffy** [Tiviacz1337/PizzaCraft#87]
So I created a server with this mod and when loading a world, the server crash, I also tried to load a world with the mod but It also crash.
There's the crash log (from the server):
[Crashserver-1.19.txt](https://github.com/Tiviacz1337/PizzaCraft/files/10395085/Crashserver-1.19.txt) or:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/11/23, 7:30 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23130!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19-41.1.0-universal.jar%23130!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19-20220607.102129-srg.jar%23125!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19-41.1.0.jar%2365!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2353!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at com.tiviacz.pizzacraft.init.ModBlockEntityTypes.<clinit>(ModBlockEntityTypes.java:12) ~[PizzaCraft-1.19-6.0.0.jar%23115!/:1.19-6.0.0] {re:classloading,pl:rei_plugin_compatibilities:B}
-- MOD pizzacraft --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23127!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23126!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: /server/mods/PizzaCraft-1.19-6.0.0.jar
	Failure message: PizzaCraft (pizzacraft) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 6.0.0
	Mod Issue URL: https://github.com/Tiviacz1337/PizzaCraft/issues
	Exception message: java.lang.NoSuchFieldError: BLOCK_ENTITIES
Stacktrace:
	at com.tiviacz.pizzacraft.init.ModBlockEntityTypes.<clinit>(ModBlockEntityTypes.java:12) ~[PizzaCraft-1.19-6.0.0.jar%23115!/:1.19-6.0.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.tiviacz.pizzacraft.PizzaCraft.<init>(PizzaCraft.java:56) ~[PizzaCraft-1.19-6.0.0.jar%23115!/:1.19-6.0.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23127!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23126!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.4.0-96-generic
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 515265536 bytes (491 MiB) / 1025507328 bytes (978 MiB) up to 2051014656 bytes (1956 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7543 32-Core Processor
	Identifier: AuthenticAMD Family 25 Model 1 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 8
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16054.34
	Virtual memory used (MB): 29116.48
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=255M -Xmx1955M -Xms978M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |COMMON_SET|Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.3.jar                |More Villagers                |morevillagers                 |4.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.580.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.580             |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.1.1-mc1.19forge.jar                 |Macaw's Windows               |mcwwindows                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		easy_villagers-1.19-1.0.8.jar                     |Easy Villagers                |easy_villagers                |1.19-1.0.8          |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.19.0-3.7.jar                      |Villager Names                |villagernames                 |3.7                 |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19-FORGE-2.0.8.jar                    |Croptopia                     |croptopia                     |2.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.30.jar                        |Collective                    |collective                    |4.30                |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.44.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.44              |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.1.jar                     |Guard Villagers               |guardvillagers                |1.19-1.5.1          |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.0.7-mc1.19.jar                        |Macaw's Doors                 |mcwdoors                      |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.13.60-forge.jar                    |Architectury                  |architectury                  |5.13.60             |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.0.2-mc1.19.jar                    |Macaw's Furniture             |mcwfurnitures                 |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		fastfooddelight-1.19-1.2.3.jar                    |https://github.com/akaneoMT/Fa|fastfooddelight               |1.19-1.2.3          |COMMON_SET|Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v4.0.18-1.19-Forge.jar                 |Puzzles Lib                   |puzzleslib                    |4.0.18              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		blueprint-1.19-6.0.7.jar                          |Blueprint                     |blueprint                     |6.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		abnormals_delight-1.19-4.0.0.jar                  |Abnormals Delight             |abnormals_delight             |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		PizzaCraft-1.19-6.0.0.jar                         |PizzaCraft                    |pizzacraft                    |6.0.0               |ERROR     |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.3-368.jar                                 |Quark                         |quark                         |3.3-368             |COMMON_SET|Manifest: NOSIGNATURE
		ctov-3.1.4.jar                                    |ChoiceTheorem's Overhauled Vil|ctov                          |3.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		Delightful-1.19-3.2.1.jar                         |Delightful                    |delightful                    |3.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		TradingPost-v4.0.1-1.19-Forge.jar                 |Trading Post                  |tradingpost                   |4.0.1               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		mcw-lights-1.0.4-mc1.19.jar                       |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 4cc3312b-3c87-4a72-bd5d-d9e9d7fb7ba8
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Comment by Tiviacz1337** [comment]
1.19 is not supported
