### ISSUE TITLE
Server Crash - NoClassDefFoundError

### ISSUE THREAD

**Issue by nephatrine** [Tiviacz1337/PizzaCraft#9]
Looks like PizzaCraft-1.12.2-1.4.0 is trying to reference clientside classes even on dedicated server:

```
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.tiviacz.pizzacraft.objects.item.ItemPizzaShield.func_77653_i(ItemPizzaShield.java:38)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1047)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
	at net.minecraft.stats.StatList.reinit(StatList.java:346)
```

**Comment by Tiviacz1337** [comment]
Please re-download file. It has the same name, but this issue is actually fixed.

**Comment by nephatrine** [comment]
fyi this worked. Please increment version # when making changes as otherwise there isn't a good way to know whether using the latest.
